// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Stackit.Outputs
{

    [OutputType]
    public sealed class GetApplicationLoadBalancerListenerHttpsResult
    {
        /// <summary>
        /// TLS termination certificate configuration.
        /// </summary>
        public readonly Outputs.GetApplicationLoadBalancerListenerHttpsCertificateConfigResult CertificateConfig;

        [OutputConstructor]
        private GetApplicationLoadBalancerListenerHttpsResult(Outputs.GetApplicationLoadBalancerListenerHttpsCertificateConfigResult certificateConfig)
        {
            CertificateConfig = certificateConfig;
        }
    }
}
