// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Stackit.Outputs
{

    [OutputType]
    public sealed class GetCdnDistributionConfigOptimizerResult
    {
        public readonly bool Enabled;

        [OutputConstructor]
        private GetCdnDistributionConfigOptimizerResult(bool enabled)
        {
            Enabled = enabled;
        }
    }
}
