// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Stackit.Outputs
{

    [OutputType]
    public sealed class GetNetworkAreaRouteDestinationResult
    {
        /// <summary>
        /// CIDRV type. Possible values are: `Cidrv4`, `Cidrv6`.
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// An CIDR string.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private GetNetworkAreaRouteDestinationResult(
            string type,

            string value)
        {
            Type = type;
            Value = value;
        }
    }
}
