// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Stackit.Outputs
{

    [OutputType]
    public sealed class ObservabilityInstanceAlertConfigReceiverOpsgenieConfig
    {
        /// <summary>
        /// The API key for OpsGenie.
        /// </summary>
        public readonly string? ApiKey;
        /// <summary>
        /// The host to send OpsGenie API requests to. Must be a valid URL
        /// </summary>
        public readonly string? ApiUrl;
        /// <summary>
        /// Priority of the alert. Possible values are: `P1`, `P2`, `P3`, `P4`, `P5`.
        /// </summary>
        public readonly string? Priority;
        /// <summary>
        /// Comma separated list of tags attached to the notifications.
        /// </summary>
        public readonly string? Tags;

        [OutputConstructor]
        private ObservabilityInstanceAlertConfigReceiverOpsgenieConfig(
            string? apiKey,

            string? apiUrl,

            string? priority,

            string? tags)
        {
            ApiKey = apiKey;
            ApiUrl = apiUrl;
            Priority = priority;
            Tags = tags;
        }
    }
}
